"""Write VERIFICATION.md from the JSON reports, so no score in the documentation is typed by hand.

Missing reports are stated as "Not evaluated". Usage:
    python scripts/make_verification_doc.py
"""

from __future__ import annotations

import json
import math

from rainpp.config import PROJECT_ROOT, load_settings

REPORTS = PROJECT_ROOT / "reports"
CORRECTORS = {"A_raw_nwp": "A Raw GEFS", "B1_quantile_mapping": "B1 Quantile mapping",
              "B2_global_lgbm": "B2 Global LightGBM", "B2s_plus_static": "B2s + terrain",
              "C1_regime_features": "C1 Regime-aware", "C2_regime_split": "C2 Regime-split",
              "C3_regime_qm": "C3 Regime QM", "D_unet": "D U-Net"}


def load(name: str) -> dict | None:
    path = REPORTS / f"{name}.json"
    return json.loads(path.read_text(encoding="utf-8")) if path.is_file() else None


def f(v, digits: int = 3) -> str:
    if v is None or (isinstance(v, float) and math.isnan(v)):
        return "n/a"
    return f"{v:.{digits}f}"


def best(values: list, higher: bool) -> int | None:
    clean = [(i, v) for i, v in enumerate(values) if v is not None and not (isinstance(v, float) and math.isnan(v))]
    if not clean:
        return None
    return (max if higher else min)(clean, key=lambda x: x[1])[0]


def corrector_table(results: dict, models: list[str]) -> list[str]:
    rows = [("RMSE (mm)", lambda s: s["rmse"], False), ("MAE (mm)", lambda s: s["mae"], False),
            ("Bias (mm)", lambda s: abs(s["bias"]), False), ("Correlation", lambda s: s["correlation"], True),
            ("ETS ≥15.6 mm", lambda s: s["categorical"]["15.6"]["ets"], True),
            ("ETS ≥64.5 mm", lambda s: s["categorical"]["64.5"]["ets"], True),
            ("POD ≥64.5 mm", lambda s: s["categorical"]["64.5"]["pod"], True),
            ("FAR ≥64.5 mm", lambda s: s["categorical"]["64.5"]["far"], False),
            ("FSS ≥64.5 mm, 9×9", lambda s: s["fss"].get("64.5", {}).get("9"), True)]
    out = []
    for lead, by_model in results.items():
        present = [m for m in models if m in by_model]
        out += [f"**Lead day {lead}** ({by_model[present[0]]['n']:,} cell-days)", "",
                "| Metric | " + " | ".join(CORRECTORS.get(m, m) for m in present) + " |",
                "|---|" + "---|" * len(present)]
        for label, get, higher in rows:
            values = [get(by_model[m]) for m in present]
            shown = [by_model[m]["bias"] if label.startswith("Bias") else v for m, v in zip(present, values, strict=True)]
            b = best(values, higher)
            out.append(f"| {label} | " + " | ".join(("**" + f(v) + "**") if i == b else f(v)
                                                    for i, v in enumerate(shown)) + " |")
        out.append("")
    return out


def significance_table(sig: dict) -> list[str]:
    out = ["| Comparison | Metric | Improvement | 95% CI | Significant |", "|---|---|---|---|---|"]
    for comp, metrics in sig.items():
        for m, r in metrics.items():
            out.append(f"| {comp} | {m} | {f(r['improvement'], 4)} | [{f(r['ci95_low'], 4)}, {f(r['ci95_high'], 4)}] | "
                       f"{'yes' if r['significant'] else 'no'} |")
    return out + [""]


def probability_table(results: dict, models: list[str]) -> list[str]:
    out = ["| Target | Model | Brier | BSS vs climatology | ROC AUC | Mean p | Base rate |", "|---|---|---|---|---|---|---|"]
    for res in results.values():
        for m in models:
            s = res["all"].get(m)
            if s:
                out.append(f"| ≥{res['threshold_mm']} mm | {m} | {f(s['brier'], 5)} | {f(s['bss_vs_climatology'])} | "
                           f"{f(s['roc_auc'])} | {f(s['mean_probability'], 4)} | {f(s['base_rate'], 4)} |")
    return out + [""]


def main() -> None:
    s = load_settings()
    (tr0, tr1), (va0, va1), (te0, te1) = s.split.train, s.split.validation, s.split.test
    op = s.split.operational_test
    md = ["# Verification — SIH 26080", "",
          ("Generated by `scripts/make_verification_doc.py` from the JSON files in `reports/`; nothing here is typed "
           "by hand. All data are REAL (NOAA GEFSv12 forecasts, IMD 0.25° gridded rainfall). Bold = best in row. "
           "Unevaluated items say so."), "",
          f"Training {tr0}–{tr1} · validation {va0}–{va1} (all model choices) · test {te0}–{te1}"
          + (f" · operational test JJAS {op[0]}–{op[1]}" if op else "") + " (scored once).", ""]

    p6, p6b, p7, p8, p5 = (load(n) for n in ("phase6_validation", "phase6b_validation", "phase7_validation",
                                             "phase8_validation", "phase5_validation"))
    md += ["## 1. Rainfall correction — validation", ""]
    if p6:
        results = p6["results"]
        if p8:
            for lead, by_model in p8["results"].items():
                results[lead]["D_unet"] = by_model["D_unet"]
        md += corrector_table(results, ["A_raw_nwp", "B1_quantile_mapping", "B2_global_lgbm", "B2s_plus_static",
                                        "C1_regime_features", "C2_regime_split", "D_unet"])
        md += ["Paired 5-day block bootstrap, 95% interval of the improvement (positive = second model better):", ""]
        md += significance_table(p6["significance_vs_baseline"])
        if p8:
            md += significance_table(p8["significance"])
    else:
        md += ["Not evaluated.", ""]
    if p6b:
        md += ["### Regime-conditioned quantile mapping (C3)", ""]
        md += corrector_table({k: v for k, v in p6b["results"].items()}, ["A_raw_nwp", "B1_quantile_mapping", "C3_regime_qm"])
        md += significance_table({"C3 vs B1": p6b["significance_C3_vs_B1"]})

    md += ["## 2. Heavy-rain probability — validation", ""]
    md += (probability_table(p7["results"], ["CLIM", "RAW01", "QM01", "P_blind", "P_regime", "P_regime_cal"])
           + significance_table({f"{k}: {c}": {"brier": v} for k, d in p7["significance"].items() for c, v in d.items()})
           if p7 else ["Not evaluated.", ""])

    md += ["## 3. Regime classifier — validation", ""]
    if p5:
        md += ["| Classifier | Accuracy | Balanced accuracy | Macro F1 |", "|---|---|---|---|"]
        for name, r in p5["results"].items():
            a = r["all"]
            md.append(f"| {name} | {f(a['accuracy'])} | {f(a.get('balanced_accuracy'))} | {f(a.get('macro_f1'))} |")
        md.append("")
    else:
        md += ["Not evaluated.", ""]

    fin = load("final_evaluation")
    md += ["## 4. One-time evaluation on held-out data", ""]
    if not fin:
        md += ["Not evaluated.", ""]
    else:
        md += [f"Run {fin['run_utc']} on frozen models (hashes in `reports/final_evaluation.json`)."
               + (f" Re-run reason: {fin['rerun_reason']}." if fin.get("rerun_reason") else ""), ""]
        for key, ds in fin["datasets"].items():
            md += [f"### {key}: {ds['description']}", "",
                   f"{ds['rows']:,} cell-days, valid {ds['valid_dates'][0]} → {ds['valid_dates'][1]}.", ""]
            md += corrector_table(ds["deterministic"], ["A_raw_nwp", "B1_quantile_mapping", "B2_global_lgbm",
                                                        "C1_regime_features", "C2_regime_split", "D_unet"])
            md += probability_table(ds["probabilistic"], ["CLIM", "RAW01", "QM01", "P_regime"])
            md += significance_table(ds["significance"])
    (PROJECT_ROOT / "VERIFICATION.md").write_text("\n".join(md), encoding="utf-8")
    print("VERIFICATION.md written")


if __name__ == "__main__":
    main()
